# Generated by Django 3.2 on 2021-06-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
